/////////////////////////////////////////////////////////////////////////////
////
// This file was auto-generated by a tool at 2022-10-20 15:23:48
//
// It is recommended you DO NOT directly edit this file but instead edit
// the code-generator that generated this source file instead.
/////////////////////////////////////////////////////////////////////////////

#include "bitonic_machine.avx512.i16.generated.h"
#include "bitonic_machine.avx512.u16.generated.h"
#include "bitonic_machine.avx512.i32.generated.h"
#include "bitonic_machine.avx512.u32.generated.h"
#include "bitonic_machine.avx512.f32.generated.h"
#include "bitonic_machine.avx512.i64.generated.h"
#include "bitonic_machine.avx512.u64.generated.h"
#include "bitonic_machine.avx512.f64.generated.h"
