[project]
name = "vxsort-cpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyfunctional",
    "pandas",
    "ipython",
    "z3-solver>=4.14.1.0",
    "pytest>=8.3.5",
    "pytest-cov>=7.0.0",
    "tabulate>=0.9.0",
]

[tool.ruff]
line-length = 240
indent-width = 4

[dependency-groups]
dev = [
    "ruff>=0.14.0",
    "setuptools>=80.9.0",
]
