/////////////////////////////////////////////////////////////////////////////
////
// This file was auto-generated by a tool at 2020-07-15 16:42:33
//
// It is recommended you DO NOT directly edit this file but instead edit
// the code-generator that generated this source file instead.
/////////////////////////////////////////////////////////////////////////////

#ifndef BITONIC_SORT_AVX2_DOUBLE_H
#define BITONIC_SORT_AVX2_DOUBLE_H

#ifdef __GNUC__
#ifdef __clang__
#pragma clang attribute push (__attribute__((target("avx2"))), apply_to = any(function))
#else
#pragma GCC push_options
#pragma GCC target("avx2")
#endif
#endif

#include <limits>
#include <immintrin.h>
#include "bitonic_sort.h"

#define i2d _mm256_castsi256_pd
#define d2i _mm256_castpd_si256
#define i2s _mm256_castsi256_ps
#define s2i _mm256_castps_si256
#define s2d _mm256_castps_pd
#define d2s _mm256_castpd_ps

namespace vxsort {
namespace smallsort {

extern "C" const uint8_t mask_table_4[16];
extern "C" const uint8_t mask_table_8[64];

template<> struct bitonic<double, AVX2> {
    static const int N = 4;
    static constexpr double MAX = std::numeric_limits<double>::max();
public:

    static INLINE void sort_01v_ascending(__m256d& d01) {
            __m256d  min, max, s;

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(min, max, 0xA);

            s = _mm256_permute4x64_pd(d01, 0x1B);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(min, max, 0xC);

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(min, max, 0xA);
}
    static INLINE void sort_01v_merge_ascending(__m256d& d01) {
            __m256d  min, max, s;

            s = _mm256_permute4x64_pd(d01, 0x4E);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(min, max, 0xC);

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(min, max, 0xA);
    }
    static INLINE void sort_01v_descending(__m256d& d01) {
            __m256d  min, max, s;

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(max, min, 0xA);

            s = _mm256_permute4x64_pd(d01, 0x1B);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(max, min, 0xC);

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(max, min, 0xA);
}
    static INLINE void sort_01v_merge_descending(__m256d& d01) {
            __m256d  min, max, s;

            s = _mm256_permute4x64_pd(d01, 0x4E);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(max, min, 0xC);

            s = _mm256_shuffle_pd(d01, d01, 0x5);
            
            min = _mm256_min_pd(s, d01);
            max = _mm256_max_pd(s, d01);
            d01 = _mm256_blend_pd(max, min, 0xA);
    }
    static INLINE void sort_02v_ascending(__m256d& d01, __m256d& d02) {
        __m256d  tmp;

        sort_01v_ascending(d01);
        sort_01v_descending(d02);

        tmp = d02;
        
        d02 = _mm256_max_pd(d01, d02);
        d01 = _mm256_min_pd(d01, tmp);

        sort_01v_merge_ascending(d01);
        sort_01v_merge_ascending(d02);
    }
    static INLINE void sort_02v_descending(__m256d& d01, __m256d& d02) {
        __m256d  tmp;

        sort_01v_descending(d01);
        sort_01v_ascending(d02);

        tmp = d02;
        
        d02 = _mm256_max_pd(d01, d02);
        d01 = _mm256_min_pd(d01, tmp);

        sort_01v_merge_descending(d01);
        sort_01v_merge_descending(d02);
    }
    static INLINE void sort_02v_merge_ascending(__m256d& d01, __m256d& d02) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d02, d01);
        
        d02 = _mm256_max_pd(d02, tmp);

        sort_01v_merge_ascending(d01);
        sort_01v_merge_ascending(d02);
    }
    static INLINE void sort_02v_merge_descending(__m256d& d01, __m256d& d02) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d02, d01);
        
        d02 = _mm256_max_pd(d02, tmp);

        sort_01v_merge_descending(d01);
        sort_01v_merge_descending(d02);
    }
    static INLINE void sort_03v_ascending(__m256d& d01, __m256d& d02, __m256d& d03) {
        __m256d  tmp;

        sort_02v_ascending(d01, d02);
        sort_01v_descending(d03);

        tmp = d03;
        
        d03 = _mm256_max_pd(d02, d03);
        d02 = _mm256_min_pd(d02, tmp);

        sort_02v_merge_ascending(d01, d02);
        sort_01v_merge_ascending(d03);
    }
    static INLINE void sort_03v_descending(__m256d& d01, __m256d& d02, __m256d& d03) {
        __m256d  tmp;

        sort_02v_descending(d01, d02);
        sort_01v_ascending(d03);

        tmp = d03;
        
        d03 = _mm256_max_pd(d02, d03);
        d02 = _mm256_min_pd(d02, tmp);

        sort_02v_merge_descending(d01, d02);
        sort_01v_merge_descending(d03);
    }
    static INLINE void sort_03v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d03, d01);
        
        d03 = _mm256_max_pd(d03, tmp);

        sort_02v_merge_ascending(d01, d02);
        sort_01v_merge_ascending(d03);
    }
    static INLINE void sort_03v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d03, d01);
        
        d03 = _mm256_max_pd(d03, tmp);

        sort_02v_merge_descending(d01, d02);
        sort_01v_merge_descending(d03);
    }
    static INLINE void sort_04v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04) {
        __m256d  tmp;

        sort_02v_ascending(d01, d02);
        sort_02v_descending(d03, d04);

        tmp = d03;
        
        d03 = _mm256_max_pd(d02, d03);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d04;
        
        d04 = _mm256_max_pd(d01, d04);
        d01 = _mm256_min_pd(d01, tmp);

        sort_02v_merge_ascending(d01, d02);
        sort_02v_merge_ascending(d03, d04);
    }
    static INLINE void sort_04v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04) {
        __m256d  tmp;

        sort_02v_descending(d01, d02);
        sort_02v_ascending(d03, d04);

        tmp = d03;
        
        d03 = _mm256_max_pd(d02, d03);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d04;
        
        d04 = _mm256_max_pd(d01, d04);
        d01 = _mm256_min_pd(d01, tmp);

        sort_02v_merge_descending(d01, d02);
        sort_02v_merge_descending(d03, d04);
    }
    static INLINE void sort_04v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d03, d01);
        
        d03 = _mm256_max_pd(d03, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d04, d02);
        
        d04 = _mm256_max_pd(d04, tmp);

        sort_02v_merge_ascending(d01, d02);
        sort_02v_merge_ascending(d03, d04);
    }
    static INLINE void sort_04v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d03, d01);
        
        d03 = _mm256_max_pd(d03, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d04, d02);
        
        d04 = _mm256_max_pd(d04, tmp);

        sort_02v_merge_descending(d01, d02);
        sort_02v_merge_descending(d03, d04);
    }
    static INLINE void sort_05v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05) {
        __m256d  tmp;

        sort_04v_ascending(d01, d02, d03, d04);
        sort_01v_descending(d05);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_01v_merge_ascending(d05);
    }
    static INLINE void sort_05v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05) {
        __m256d  tmp;

        sort_04v_descending(d01, d02, d03, d04);
        sort_01v_ascending(d05);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_01v_merge_descending(d05);
    }
    static INLINE void sort_05v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_01v_merge_ascending(d05);
    }
    static INLINE void sort_05v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_01v_merge_descending(d05);
    }
    static INLINE void sort_06v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06) {
        __m256d  tmp;

        sort_04v_ascending(d01, d02, d03, d04);
        sort_02v_descending(d05, d06);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_02v_merge_ascending(d05, d06);
    }
    static INLINE void sort_06v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06) {
        __m256d  tmp;

        sort_04v_descending(d01, d02, d03, d04);
        sort_02v_ascending(d05, d06);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_02v_merge_descending(d05, d06);
    }
    static INLINE void sort_06v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_02v_merge_ascending(d05, d06);
    }
    static INLINE void sort_06v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_02v_merge_descending(d05, d06);
    }
    static INLINE void sort_07v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07) {
        __m256d  tmp;

        sort_04v_ascending(d01, d02, d03, d04);
        sort_03v_descending(d05, d06, d07);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d07;
        
        d07 = _mm256_max_pd(d02, d07);
        d02 = _mm256_min_pd(d02, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_03v_merge_ascending(d05, d06, d07);
    }
    static INLINE void sort_07v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07) {
        __m256d  tmp;

        sort_04v_descending(d01, d02, d03, d04);
        sort_03v_ascending(d05, d06, d07);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d07;
        
        d07 = _mm256_max_pd(d02, d07);
        d02 = _mm256_min_pd(d02, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_03v_merge_descending(d05, d06, d07);
    }
    static INLINE void sort_07v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        tmp = d03;
        
        d03 = _mm256_min_pd(d07, d03);
        
        d07 = _mm256_max_pd(d07, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_03v_merge_ascending(d05, d06, d07);
    }
    static INLINE void sort_07v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        tmp = d03;
        
        d03 = _mm256_min_pd(d07, d03);
        
        d07 = _mm256_max_pd(d07, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_03v_merge_descending(d05, d06, d07);
    }
    static INLINE void sort_08v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08) {
        __m256d  tmp;

        sort_04v_ascending(d01, d02, d03, d04);
        sort_04v_descending(d05, d06, d07, d08);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d07;
        
        d07 = _mm256_max_pd(d02, d07);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d08;
        
        d08 = _mm256_max_pd(d01, d08);
        d01 = _mm256_min_pd(d01, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_04v_merge_ascending(d05, d06, d07, d08);
    }
    static INLINE void sort_08v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08) {
        __m256d  tmp;

        sort_04v_descending(d01, d02, d03, d04);
        sort_04v_ascending(d05, d06, d07, d08);

        tmp = d05;
        
        d05 = _mm256_max_pd(d04, d05);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d06;
        
        d06 = _mm256_max_pd(d03, d06);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d07;
        
        d07 = _mm256_max_pd(d02, d07);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d08;
        
        d08 = _mm256_max_pd(d01, d08);
        d01 = _mm256_min_pd(d01, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_04v_merge_descending(d05, d06, d07, d08);
    }
    static INLINE void sort_08v_merge_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        tmp = d03;
        
        d03 = _mm256_min_pd(d07, d03);
        
        d07 = _mm256_max_pd(d07, tmp);

        tmp = d04;
        
        d04 = _mm256_min_pd(d08, d04);
        
        d08 = _mm256_max_pd(d08, tmp);

        sort_04v_merge_ascending(d01, d02, d03, d04);
        sort_04v_merge_ascending(d05, d06, d07, d08);
    }
    static INLINE void sort_08v_merge_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08) {
        __m256d  tmp;

        tmp = d01;
        
        d01 = _mm256_min_pd(d05, d01);
        
        d05 = _mm256_max_pd(d05, tmp);

        tmp = d02;
        
        d02 = _mm256_min_pd(d06, d02);
        
        d06 = _mm256_max_pd(d06, tmp);

        tmp = d03;
        
        d03 = _mm256_min_pd(d07, d03);
        
        d07 = _mm256_max_pd(d07, tmp);

        tmp = d04;
        
        d04 = _mm256_min_pd(d08, d04);
        
        d08 = _mm256_max_pd(d08, tmp);

        sort_04v_merge_descending(d01, d02, d03, d04);
        sort_04v_merge_descending(d05, d06, d07, d08);
    }
    static INLINE void sort_09v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_01v_descending(d09);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_01v_merge_ascending(d09);
    }
    static INLINE void sort_09v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_01v_ascending(d09);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_01v_merge_descending(d09);
    }
    static INLINE void sort_10v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_02v_descending(d09, d10);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_02v_merge_ascending(d09, d10);
    }
    static INLINE void sort_10v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_02v_ascending(d09, d10);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_02v_merge_descending(d09, d10);
    }
    static INLINE void sort_11v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_03v_descending(d09, d10, d11);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_03v_merge_ascending(d09, d10, d11);
    }
    static INLINE void sort_11v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_03v_ascending(d09, d10, d11);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_03v_merge_descending(d09, d10, d11);
    }
    static INLINE void sort_12v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_04v_descending(d09, d10, d11, d12);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_04v_merge_ascending(d09, d10, d11, d12);
    }
    static INLINE void sort_12v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_04v_ascending(d09, d10, d11, d12);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_04v_merge_descending(d09, d10, d11, d12);
    }
    static INLINE void sort_13v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_05v_descending(d09, d10, d11, d12, d13);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_05v_merge_ascending(d09, d10, d11, d12, d13);
    }
    static INLINE void sort_13v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_05v_ascending(d09, d10, d11, d12, d13);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_05v_merge_descending(d09, d10, d11, d12, d13);
    }
    static INLINE void sort_14v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_06v_descending(d09, d10, d11, d12, d13, d14);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_06v_merge_ascending(d09, d10, d11, d12, d13, d14);
    }
    static INLINE void sort_14v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_06v_ascending(d09, d10, d11, d12, d13, d14);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_06v_merge_descending(d09, d10, d11, d12, d13, d14);
    }
    static INLINE void sort_15v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14, __m256d& d15) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_07v_descending(d09, d10, d11, d12, d13, d14, d15);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d15;
        
        d15 = _mm256_max_pd(d02, d15);
        d02 = _mm256_min_pd(d02, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_07v_merge_ascending(d09, d10, d11, d12, d13, d14, d15);
    }
    static INLINE void sort_15v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14, __m256d& d15) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_07v_ascending(d09, d10, d11, d12, d13, d14, d15);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d15;
        
        d15 = _mm256_max_pd(d02, d15);
        d02 = _mm256_min_pd(d02, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_07v_merge_descending(d09, d10, d11, d12, d13, d14, d15);
    }
    static INLINE void sort_16v_ascending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14, __m256d& d15, __m256d& d16) {
        __m256d  tmp;

        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_08v_descending(d09, d10, d11, d12, d13, d14, d15, d16);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d15;
        
        d15 = _mm256_max_pd(d02, d15);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d16;
        
        d16 = _mm256_max_pd(d01, d16);
        d01 = _mm256_min_pd(d01, tmp);

        sort_08v_merge_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_08v_merge_ascending(d09, d10, d11, d12, d13, d14, d15, d16);
    }
    static INLINE void sort_16v_descending(__m256d& d01, __m256d& d02, __m256d& d03, __m256d& d04, __m256d& d05, __m256d& d06, __m256d& d07, __m256d& d08, __m256d& d09, __m256d& d10, __m256d& d11, __m256d& d12, __m256d& d13, __m256d& d14, __m256d& d15, __m256d& d16) {
        __m256d  tmp;

        sort_08v_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_08v_ascending(d09, d10, d11, d12, d13, d14, d15, d16);

        tmp = d09;
        
        d09 = _mm256_max_pd(d08, d09);
        d08 = _mm256_min_pd(d08, tmp);

        tmp = d10;
        
        d10 = _mm256_max_pd(d07, d10);
        d07 = _mm256_min_pd(d07, tmp);

        tmp = d11;
        
        d11 = _mm256_max_pd(d06, d11);
        d06 = _mm256_min_pd(d06, tmp);

        tmp = d12;
        
        d12 = _mm256_max_pd(d05, d12);
        d05 = _mm256_min_pd(d05, tmp);

        tmp = d13;
        
        d13 = _mm256_max_pd(d04, d13);
        d04 = _mm256_min_pd(d04, tmp);

        tmp = d14;
        
        d14 = _mm256_max_pd(d03, d14);
        d03 = _mm256_min_pd(d03, tmp);

        tmp = d15;
        
        d15 = _mm256_max_pd(d02, d15);
        d02 = _mm256_min_pd(d02, tmp);

        tmp = d16;
        
        d16 = _mm256_max_pd(d01, d16);
        d01 = _mm256_min_pd(d01, tmp);

        sort_08v_merge_descending(d01, d02, d03, d04, d05, d06, d07, d08);
        sort_08v_merge_descending(d09, d10, d11, d12, d13, d14, d15, d16);
    }

        static NOINLINE void sort_01v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 0), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_01v_ascending(d01);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 0), mask, d01);
    }

        static NOINLINE void sort_02v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 1), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_02v_ascending(d01, d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 1), mask, d02);
    }

        static NOINLINE void sort_03v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 2), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_03v_ascending(d01, d02, d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 2), mask, d03);
    }

        static NOINLINE void sort_04v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 3), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_04v_ascending(d01, d02, d03, d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 3), mask, d04);
    }

        static NOINLINE void sort_05v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 4), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_05v_ascending(d01, d02, d03, d04, d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 4), mask, d05);
    }

        static NOINLINE void sort_06v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 5), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_06v_ascending(d01, d02, d03, d04, d05, d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 5), mask, d06);
    }

        static NOINLINE void sort_07v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 6), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_07v_ascending(d01, d02, d03, d04, d05, d06, d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 6), mask, d07);
    }

        static NOINLINE void sort_08v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 7), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_08v_ascending(d01, d02, d03, d04, d05, d06, d07, d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 7), mask, d08);
    }

        static NOINLINE void sort_09v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 8), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_09v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 8), mask, d09);
    }

        static NOINLINE void sort_10v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 9), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_10v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 9), mask, d10);
    }

        static NOINLINE void sort_11v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 10), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_11v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 10), mask, d11);
    }

        static NOINLINE void sort_12v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 10));
        __m256d d12 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 11), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_12v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 10), d11);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 11), mask, d12);
    }

        static NOINLINE void sort_13v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 10));
        __m256d d12 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 11));
        __m256d d13 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 12), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_13v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12, d13);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 10), d11);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 11), d12);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 12), mask, d13);
    }

        static NOINLINE void sort_14v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 10));
        __m256d d12 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 11));
        __m256d d13 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 12));
        __m256d d14 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 13), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_14v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12, d13, d14);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 10), d11);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 11), d12);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 12), d13);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 13), mask, d14);
    }

        static NOINLINE void sort_15v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 10));
        __m256d d12 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 11));
        __m256d d13 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 12));
        __m256d d14 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 13));
        __m256d d15 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 14), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_15v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12, d13, d14, d15);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 10), d11);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 11), d12);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 12), d13);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 13), d14);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 14), mask, d15);
    }

        static NOINLINE void sort_16v_alt(double *ptr, int remainder) {
            const auto mask = _mm256_cvtepi8_epi64(_mm_loadu_si128((__m128i*)(mask_table_4 + remainder * N)));

        __m256d d01 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 0));
        __m256d d02 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 1));
        __m256d d03 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 2));
        __m256d d04 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 3));
        __m256d d05 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 4));
        __m256d d06 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 5));
        __m256d d07 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 6));
        __m256d d08 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 7));
        __m256d d09 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 8));
        __m256d d10 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 9));
        __m256d d11 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 10));
        __m256d d12 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 11));
        __m256d d13 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 12));
        __m256d d14 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 13));
        __m256d d15 = _mm256_loadu_pd((double const *) ((__m256d const *) ptr + 14));
        __m256d d16 = _mm256_or_pd(_mm256_maskload_pd((double const *) ((__m256d const *) ptr + 15), mask), _mm256_andnot_pd(i2d(mask), _mm256_set1_pd(MAX)));
        sort_16v_ascending(d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, d12, d13, d14, d15, d16);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 0), d01);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 1), d02);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 2), d03);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 3), d04);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 4), d05);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 5), d06);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 6), d07);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 7), d08);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 8), d09);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 9), d10);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 10), d11);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 11), d12);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 12), d13);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 13), d14);
        _mm256_storeu_pd((double *) ((__m256d *)  ptr + 14), d15);
        _mm256_maskstore_pd((double *) ((__m256d *)  ptr + 15), mask, d16);
    }
    static void sort(double *ptr, size_t length);

};
}
}

#undef i2d
#undef d2i
#undef i2s
#undef s2i
#undef s2d
#undef d2s

#ifdef __GNUC__
#ifdef __clang__
#pragma clang attribute pop
#else
#pragma GCC pop_options
#endif
#endif
#endif
    
