/////////////////////////////////////////////////////////////////////////////
////
// This file was auto-generated by a tool at 2022-10-08 19:28:11
//
// It is recommended you DO NOT directly edit this file but instead edit
// the code-generator that generated this source file instead.
/////////////////////////////////////////////////////////////////////////////

#include "bitonic_machine.avx2.i16.generated.h"
#include "bitonic_machine.avx2.u16.generated.h"
#include "bitonic_machine.avx2.i32.generated.h"
#include "bitonic_machine.avx2.u32.generated.h"
#include "bitonic_machine.avx2.f32.generated.h"
#include "bitonic_machine.avx2.i64.generated.h"
#include "bitonic_machine.avx2.u64.generated.h"
#include "bitonic_machine.avx2.f64.generated.h"
